apiVersion: v2
name: vault-raft-snapshot-agent
description: Vault Raft Snapshot Agent takes periodic snapshots of vault's raft database and writes it to a local file or an S3 bucket
keywords:
- vault-raft-snapshot-agent
- vault
- backup
- snapshots
- raft
- integrated storage


type: application
version: 0.1.3
appVersion: "v0.5.1"

home: https://github.com/Argelbargel/vault-raft-snapshot-agent
sources:
  - https://github.com/Argelbargel/vault-raft-snapshot-agent-helm/
maintainers:
- name: Argelbargel
