apiVersion: v2
name: vault-raft-snapshot-agent
type: application
version: 0.2.0
appVersion: "v0.6.0"
description: Vault Raft Snapshot Agent takes periodic snapshots of Vault's Raft database and stores them on a local volume or an remote S3 bucket
keywords:
- vault-raft-snapshot-agent
- vault
- backup
- snapshots
- raft
- integrated storage
home: https://argelbargel.github.io/vault-raft-snapshot-agent-helm/
sources:
- https://github.com/Argelbargel/vault-raft-snapshot-agent-helm/
maintainers:
- name: Argelbargel
annotations:
  artifacthub.io/category: security
  artifacthub.io/license: MIT
  artifacthub.io/images: |
    - name: vault-raft-snapshot-agent
      image: ghcr.io/argelbargel/vault-raft-snapshot-agent:v0.6.0
      platforms:
        - linux/amd64
        - linux/arm64
        - linux/arm/v7
  artifacthub.io/recommendations: |
    - url: https://artifacthub.io/packages/helm/hashicorp/vault
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/changes: |
    - improves documentation & metadata
