apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "vault-raft-snapshot-agent.fullname" . }}
  namespace: {{ template "vault-raft-snapshot-agent.namespace" . }}
  labels:
    helm.sh/chart: {{ include "vault-raft-snapshot-agent.chart" . }}
    app.kubernetes.io/name: {{ include "vault-raft-snapshot-agent.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    component: snapshot-agent
data:
  snapshot.yaml: |-
    {{- $config := deepCopy .Values.config -}}
    {{- if $config.uploaders.local.enabled -}}
    {{- $_ := set $config.uploaders "local" (pick $config.uploaders.local "path") -}}
    {{- else -}}
    {{- $_ := unset $config.uploaders "local" -}}
    {{- end -}}
    {{- toYaml $config | nindent 4 -}}
