apiVersion: "apps/v1"
kind: Deployment
metadata:
  name: {{ template "vault-raft-snapshot-agent.fullname" . }}
  namespace: {{ template "vault-raft-snapshot-agent.namespace" . }}
  labels:
    helm.sh/chart: {{ template "vault-raft-snapshot-agent.chart" . }}
    app.kubernetes.io/name: {{ template "vault-raft-snapshot-agent.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    component: snapshot-agent
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "vault-raft-snapshot-agent.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      component: snapshot-agent
  replicas: 1
  strategy:
    type: {{ .Values.deployment.strategy.type }}
  {{- with .Values.deployment.revisionHistoryLimit }}
  revisionHistoryLimit: {{ .Values.deployment.revisionHistoryLimit }}
  {{- end }}
  template:
    metadata:
      labels:
        helm.sh/chart: {{ template "vault-raft-snapshot-agent.chart" . }}
        app.kubernetes.io/name: {{ include "vault-raft-snapshot-agent.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        component: snapshot-agent
      annotations:
        checksum/config: {{ include (print .Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- if .Values.deployment.extraAnnotations }}
        {{ toYaml .Values.deployment.extraAnnotations | indent 8 }}
        {{- end }}
    spec:
      restartPolicy: Always
      containers:
        - name: {{ include "vault-raft-snapshot-agent.name" . }}
          {{- with .Values.deployment.image }}
          image: {{ .repo }}:{{ .tag | default $.Chart.AppVersion }}
          imagePullPolicy: {{ .pullPolicy }}
          {{- end }}
          {{- if not (empty .Values.deployment.extraEnv) }}
          env: {{ toYaml .Values.deployment.extraEnv | nindent 12 }}
          {{- end }}
          {{- if not (empty .Values.deployment.extraEnvFrom) }}
          envFrom: {{ toYaml .Values.deployment.extraEnvFrom | nindent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: /etc/vault.d/
              name: config
              readOnly: true
            {{- if .Values.config.snapshots.storages.local.enabled }}
            - mountPath: {{ .Values.config.snapshots.storages.local.path }}
              name: snapshots
            {{- end }}
            {{- range $volume := .Values.deployment.extraVolumes }}
            - mountPath: {{ required "volume mountPath is required" $volume.mountPath }}
              name: {{ required "volume name is required" $volume.name }}
              {{- with $volume.readOnly }}
              readOnly: {{ $volume.readOnly }}
              {{- end }}
            {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "vault-raft-snapshot-agent.fullname" . }}
        {{- if .Values.config.snapshots.storages.local.enabled }}
        - name: snapshots
          {{- with .Values.config.snapshots.storages.local.volume }}
          {{- if .persistentVolumeClaim }}
          persistentVolumeClaim:
            claimName: {{ include "vault-raft-snapshot-agent.fullname" $ }}
          {{- else }}
          {{- toYaml . | nindent 10 -}}
          {{- end }}
          {{- end }}
        {{- end }}
        {{- range $volume := .Values.deployment.extraVolumes }}
        - name: {{ required "volume name is required" (get $volume "name") }}
          {{- toYaml (omit $volume "name" "mountPath" "readOnly") | nindent 10 }}
        {{- end }}
