apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "vault-raft-snapshot-agent.fullname" . }}
  namespace: {{ template "vault-raft-snapshot-agent.namespace" . }}
  labels:
    helm.sh/chart: {{ include "vault-raft-snapshot-agent.chart" . }}
    app.kubernetes.io/name: {{ include "vault-raft-snapshot-agent.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    component: snapshot-agent
data:
  snapshot.json: |-
    {{- $config := deepCopy .Values.config -}}
    {{- if $config.local_storage.enabled -}}
    {{- $_ := set $config "local_storage" (pick $config.local_storage "path") -}}
    {{- else -}}
    {{- $_ := unset $config "local_storage" -}}
    {{- end -}}
    {{- toJson $config | nindent 4 -}}
