name: Lint and Test Helm-Charts

on:
  workflow_dispatch:
  push:
    branches:
    - "**"
    tags-ignore:
    - "v**"
  pull_request:
    branches:
    - "**"
    tags-ignore:
    - "v**"

jobs:
  check-charts:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Determine latest (Pre-)Release
      uses: cardinalby/git-get-release-action@v1
      id: latest-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        latest: true
        draft: false
        prereleased: true

    - name: Dump context
      run: |
        echo ${{ toJson(github) }}
        echo ${{ toJson(steps.latest-release.outputs )}}

