name: Lint and Test Helm-Charts

on:
  workflow_dispatch:
    inputs:
      target-branch:
        description: "check charts changed based on branch/tag"
        type: string
        required: false
  workflow_call:
    inputs:
      target-branch:
        type: string
        required: false
  push:
    branches:
    - "**"
    tags-ignore:
    - "v**"
    paths:
    - "charts/**"
    - ".github/workflows/checks.yml"
  pull_request:
    branches:
    - "**"
    tags-ignore:
    - "v**"
    paths:
    - "charts/**"
    - ".github/workflows/checks.yml"

concurrency:
  group: checks-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-charts:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set-up chart testing
      uses: helm/chart-testing-action@v2.6.0

    - name: Determine check-parameters
      id: params
      run: |
        PARAMS=--all

        if [[ "${{ inputs.target-branch }}" =~ ^v[[:digit:]] ]] && [ "${{ inputs.target-branch }}" != "v0.0.0" ]; then
          PARAMS="--target-branch ${{ inputs.target-branch }}"
        elif [ "${{ github.event_name}}" == "pull_request" ]; then
          PARAMS="--target-branch ${{ github.event.repository.default_branch }}"
        fi

        echo "params=$PARAMS" >> "$GITHUB_OUTPUT"

    - name: Determine changes
      if: steps.params.outputs.params != '--all'
      id: changes
      run: |
        CHANGES=$(ct list-changed ${{ steps.params.outputs.params }})
        if [ -z "$CHANGES" ]; then
          echo "changed=false" >> "$GITHUB_OUTPUT"
        fi

    - name: Set up Helm
      if: steps.changes.outputs.changed != 'false'
      uses: azure/setup-helm@v4
      with:
        version: v3.12.1

    - name: Lint changed charts
      if: steps.changes.outputs.changed != 'false'
      run: |
        ct lint ${{steps.params.outputs.params }}

    - name: Create kind cluster
      if: steps.changes.outputs.changed != 'false'
      uses: helm/kind-action@v1.9.0

    - name: Install charts
      if: steps.changes.outputs.changed != 'false'
      run: |
        ct install ${{steps.params.outputs.params }}

