name: Lint and Test Helm-Charts

on:
  workflow_dispatch:
    inputs:
      target-branch:
        description: "check charts changed based on branch/tag"
        type: string
        required: false
  workflow_call:
    inputs:
      target-branch:
        type: string
        required: false
  push:
    branches:
    - "**"
    tags-ignore:
    - "v**"
  pull_request:
    branches:
    - "**"
    tags-ignore:
    - "v**"

jobs:
  check-charts:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.12.1

    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        check-latest: true

    - name: Set-up chart testing
      uses: helm/chart-testing-action@v2.4.0

    - name: Dump context

      run: |
        echo "github"
        cat <<EOF
         ${{ toJson(github) }}
        EOF
        echo "latest-release:"
        cat << EOF
          ${{ toJson( steps.latest-release.outputs )}}
        EOF

    - name: Determine changes
      id: changes
      run: |
        PARAMS=--all
        CHANGED=true

        if [ "${{ inputs.target-branch }}" != "" ]; then
          PARAMS=--target-branch=${{ inputs.target-branch }}
        elif [ "${{ github.event_name}}" == "pull_request" ]; then
          PARAMS=--target-branch=${{ github.event.repository.default_branch }}
        fi

        if [ "$PARAMS" != "--all" ]; then
          CHANGES=$(ct list-changed $PARAMS)
          if [[ -z "$CHANGES" ]]; then
            CHANGED=false
          fi
        fi

        echo "params=$PARAMS" >> "$GITHUB_OUTPUT"
        echo "changed=$CHANGED" >> "$GITHUB_OUTPUT"

    - name: Lint changed charts
      if: steps.changes.outputs.changed
      run: |
        ct lint ${{steps.changes.outputs.params }}

    - name: Create kind cluster
      if: steps.changes.outputs.changed
      uses: helm/kind-action@v1.7.0

    - name: Install charts
      if: steps.changes.outputs.changed
      run: |
        ct install ${{steps.changes.outputs.params }}

