name: Release

on:
  workflow_dispatch:
  push:
    branches:
    - workflow
    tags-ignore:
    - "**-v**"
    paths:
    - '**/Chart.yaml'

env:
  CHARTS_DIR: ./charts

jobs:
  check-charts:
    uses: ./.github/workflows/check-helm-charts.yml

  release-charts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

    - name: Install Helm
      uses: azure/setup-helm@v3

    - name: Run chart-releaser
      uses: helm/chart-releaser-action@v1.5.0
      with:
        charts_dir: ${{ env.CHARTS_DIR }}
      env:
        CR_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
