name: Release

on:
  workflow_dispatch:
    inputs:
      skip-checks:
        description: "Skip checks before releasing?"
        type: boolean
        default: false
  push:
    branches:
    - master
    tags-ignore:
    - "**-v**"
    paths:
    - 'charts/**/Chart.yaml'

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

env:
  CHARTS_DIR: ./charts

jobs:
  determine-release-version:
    runs-on: ubuntu-latest
    outputs:
      current: ${{ steps.release-version.outputs.version_tag }}
      previous: v${{ steps.release-version.outputs.previous_version }}

    steps:
    - name: Determine Release-Version
      id: release-version
      uses: paulhatch/semantic-version@v5.1.0
      with:
        tag_prefix: "v"
        version_format: "${major}.${minor}.${patch}"
        search_commit_body: true

    - name: Dump release-version-infos
      run: |
        cat << EOF
          ${{ toJson(steps.release-version.outputs )}}
        EOF

  check-charts:
    if: "! ${{ inputs.skip-checks }}"
    needs:
    - determine-release-version
    uses: ./.github/workflows/checks.yml
    with:
      target-branch: ${{ needs.determine-release-version.previous }}

  release-charts:
    runs-on: ubuntu-latest
    needs:
    - determine-release-version
    - check-charts

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

    - name: Install Helm
      uses: azure/setup-helm@v3

    - name: Run chart-releaser
      uses: helm/chart-releaser-action@v1.5.0
      with:
        charts_dir: ${{ env.CHARTS_DIR }}
      env:
        CR_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        CR_RELEASE_NAME_TEMPLATE: ${{ needs.determine-release-version.outputs.current }}
