name: Release

on:
  workflow_dispatch:
  push:
    branches:
    - workflow
    tags-ignore:
    - "**-v**"
    paths:
    - '**/Chart.yaml'

env:
  CHARTS_DIR: ./charts

jobs:
  determine-previous-release:
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.latest-release.outputs.tag_name }}

    steps:
    - name: Determine latest (Pre-)Release
      id: latest-release
      uses: cardinalby/git-get-release-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        latest: true
        draft: false
        prerelease: true
        doNotFailIfNotFound: true


  check-charts:
    needs:
    - determine-previous-release
    uses: ./.github/workflows/checks.yml
    with:
      target-branch: ${{ needs.determine-previous-release.outputs.tag_name }}

