name: Release README

on:
  workflow_dispatch:
  push:
    tags:
    - "v**"
    paths:
    - 'README.md'

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release-readme:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          cp -f README.md ${{ runner.temp }}/README.md
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
      - run: |
          cp -f ${{ runner.temp }}/README.md .
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add README.md
          git commit --signoff -m "Sync README for Release ${{github.ref_name}}"
          git push  